spring:
  datasource:
    url: jdbc:h2:mem:sdw2025
    username: sdw2025
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update  # Alterado para evitar perda de dados em cada execução
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.cwcdev.dio
  show-actuator: true
